### PR TITLE
BUGFIX: Fixed bug in configCLI code

### LINKED ISSUE #22: Config menu still not bulletproof
Still need to stress-test the config menu to make sure it's bulletproof in terms of saving all settings every time. I feel like I've seen issues with certain configs keeping the MODE and offsetx settings after booting out of config menu.

### PR DESCRIPTION
**Pull request by ChaseStewart**
Resolves #22 

When we were changing the color of the config, we were not also loading the config- this resulted in a sort of "stamping effect" when changing between colors that had different configs. This should be the last issue with EEPROM saved settings.

Also:
* Bumped version to 1.0.0 !!!
* Fixed syntax issue with PollForSerial when #debug was defined
* Removed OBE saveColorHandler callback command (every setting effectively does this now).

### CODE REVIEW

File: Software/PaddleFirmware/Main/ConfigConsole.cpp [hunk 1]
```diff
@@ -125,7 +125,8 @@ bool selectColorHandler(Commander &Cmdr)
     Cmdr.println("ERROR: only accepted values are \"BLUE\", \"CYAN\", \"GREEN\", \"PURPLE\", \"RED\",  \"YELLOW\", \"WHITE\"!");
     return false;  
   }
-  
+
+  current_config = loadConfigFromEEPROM(config_state);
```
Comment (ChaseStewart) [inline Software/PaddleFirmware/Main/ConfigConsole.cpp:129]: This is the big thing that was missing here.
